// Script to generate a massive, 100% child-friendly curriculum word bank for Kibo Words (2,000-2,500+ words)
import fs from 'fs';
import path from 'path';

// Comprehensive, child-friendly word dictionary for all 8 tiers
const TIER_DATA = {
  1: [
    // --- TIER 1: CVC & Sight Words & Early Phonics (Kindergarten - Grade 1) ---
    // Short A
    { word: 'cat', hint: 'A friendly pet that meows and purrs.' },
    { word: 'bat', hint: 'A flying animal or a wooden stick used in baseball.' },
    { word: 'hat', hint: 'Something cozy you wear on your head.' },
    { word: 'mat', hint: 'A small rug placed on the floor near the doorway.' },
    { word: 'rat', hint: 'A furry little animal with whiskers and a long tail.' },
    { word: 'cap', hint: 'A hat with a curved visor in the front.' },
    { word: 'map', hint: 'A colorful drawing showing roads, towns, and rivers.' },
    { word: 'tap', hint: 'To touch something lightly or where water flows out.' },
    { word: 'nap', hint: 'A short, refreshing sleep during the afternoon.' },
    { word: 'bag', hint: 'A container made of cloth or paper used to carry things.' },
    { word: 'tag', hint: 'A label on a shirt or a fun playground chasing game.' },
    { word: 'rag', hint: 'A soft piece of cloth used for wiping up spills.' },
    { word: 'van', hint: 'A spacious motor vehicle larger than a car.' },
    { word: 'pan', hint: 'A metal cooking dish with a handle used on the stove.' },
    { word: 'fan', hint: 'A machine with spinning blades that blows cool air.' },
    { word: 'man', hint: 'A grown-up male person.' },
    { word: 'jam', hint: 'Sweet fruit spread made from berries for toast.' },
    { word: 'ham', hint: 'A slice of food often served for lunch in sandwiches.' },
    { word: 'dad', hint: 'A loving father.' },
    { word: 'cab', hint: 'A yellow taxi car that gives people rides.' },
    { word: 'lab', hint: 'A room where scientists do exciting experiments.' },
    { word: 'wax', hint: 'The smooth material that melts on a birthday candle.' },
    { word: 'pad', hint: 'A stack of paper sheets for drawing or writing notes.' },
    { word: 'sad', hint: 'Feeling unhappy; the opposite of joyful.' },
    { word: 'lad', hint: 'A friendly word for a young boy.' },
    { word: 'tab', hint: 'A small flap you click or pull on a folder or screen.' },
    { word: 'wag', hint: 'What a happy puppy does with its tail.' },
    { word: 'gap', hint: 'An open space between two things.' },
    { word: 'lap', hint: 'The flat area between your knees when sitting.' },
    { word: 'can', hint: 'A metal container holding soup or juice.' },
    { word: 'ran', hint: 'Moved fast on foot in the past.' },
    { word: 'tan', hint: 'A light golden-brown color like sand.' },
    { word: 'yam', hint: 'A sweet orange root vegetable similar to a potato.' },
    { word: 'ram', hint: 'A male sheep with big curled horns.' },
    { word: 'dam', hint: 'A strong wall built across a river to hold back water.' },

    // Short E
    { word: 'bed', hint: 'A soft, warm place where you sleep at night.' },
    { word: 'red', hint: 'The bright color of a ripe strawberry or a stop sign.' },
    { word: 'net', hint: 'Interwoven strings used to catch a soccer ball or fish.' },
    { word: 'pet', hint: 'A cuddly animal companion like a puppy or kitten.' },
    { word: 'wet', hint: 'Covered with water or raindrops; not dry.' },
    { word: 'set', hint: 'A group of matching items, like a set of blocks.' },
    { word: 'ten', hint: 'The number that comes right after nine (10).' },
    { word: 'pen', hint: 'An instrument used for writing with colored ink.' },
    { word: 'hen', hint: 'A female chicken that clucks and lays fresh eggs.' },
    { word: 'men', hint: 'More than one adult male person.' },
    { word: 'leg', hint: 'The lower body limb used for walking and jumping.' },
    { word: 'peg', hint: 'A small wooden or plastic pin on a coat rack.' },
    { word: 'jet', hint: 'A fast airplane powered by powerful engines.' },
    { word: 'web', hint: 'A delicate silky net spun by a garden spider.' },
    { word: 'gem', hint: 'A precious, sparkling jewel like a ruby or emerald.' },
    { word: 'den', hint: 'A cozy home for a bear or a comfortable family room.' },
    { word: 'vet', hint: 'An animal doctor who helps sick pets get well.' },
    { word: 'fed', hint: 'Gave yummy food to a pet or friend.' },
    { word: 'led', hint: 'Guided others along a path in the past.' },
    { word: 'get', hint: 'To receive, obtain, or fetch something.' },
    { word: 'let', hint: 'To give permission or allow something to happen.' },
    { word: 'met', hint: 'Shook hands with a new friend in the past.' },
    { word: 'beg', hint: 'To ask very politely or nicely for a treat.' },
    { word: 'egg', hint: 'An oval shell laid by birds that you can scramble.' },
    { word: 'hem', hint: 'The folded and stitched bottom edge of a dress or shirt.' },
    { word: 'yes', hint: 'A positive answer; the opposite of no.' },
    { word: 'yet', hint: 'Up until now; as of this moment.' },

    // Short I
    { word: 'pig', hint: 'A cheerful pink farm animal that says oink.' },
    { word: 'big', hint: 'Very large in size; the opposite of tiny.' },
    { word: 'dig', hint: 'To scoop up dirt with a garden shovel.' },
    { word: 'wig', hint: 'A cap made of artificial hair worn in costumes.' },
    { word: 'pin', hint: 'A tiny pointed metal fastener used on clothing.' },
    { word: 'win', hint: 'To be first in a race or achieve victory in a game.' },
    { word: 'bin', hint: 'A storage box used to organize toys or recycling.' },
    { word: 'tin', hint: 'A shiny silver metal used to make cans.' },
    { word: 'lip', hint: 'Either of the two soft edges of your mouth.' },
    { word: 'tip', hint: 'The very top point of a pencil or helpful advice.' },
    { word: 'sip', hint: 'To drink a small amount of lemonade slowly.' },
    { word: 'rip', hint: 'To tear paper or fabric apart gently.' },
    { word: 'sit', hint: 'To rest comfortably on a chair.' },
    { word: 'hit', hint: 'To tap a baseball with a wooden bat.' },
    { word: 'fit', hint: 'Just the right size; also healthy and strong.' },
    { word: 'lid', hint: 'A removable top cover for a jar or teapot.' },
    { word: 'kid', hint: 'A cheerful young child or a baby goat.' },
    { word: 'fix', hint: 'To repair a toy that is broken.' },
    { word: 'mix', hint: 'To stir different ingredients together in a bowl.' },
    { word: 'six', hint: 'The number between five and seven (6).' },
    { word: 'rib', hint: 'One of the curved bones protecting your chest.' },
    { word: 'bib', hint: 'A cloth tied around a baby neck during meals.' },
    { word: 'dip', hint: 'To lower something quickly into water or salsa.' },
    { word: 'hip', hint: 'The side of your body just below your waist.' },
    { word: 'zip', hint: 'To fasten a jacket using a sliding zipper.' },
    { word: 'bit', hint: 'A small piece or took a bite of an apple.' },
    { word: 'kit', hint: 'A set of special tools, like a craft kit.' },
    { word: 'lit', hint: 'Brightened with a candle or flashlight.' },
    { word: 'pit', hint: 'The large hard seed inside a peach or cherry.' },
    { word: 'hid', hint: 'Stayed out of sight during hide and seek.' },
    { word: 'did', hint: 'Completed a chore or activity in the past.' },
    { word: 'fin', hint: 'The wing-like part a fish uses to swim.' },
    { word: 'fig', hint: 'A sweet, soft purple fruit with tiny seeds inside.' },

    // Short O
    { word: 'dog', hint: 'A loyal pet that wags its tail and barks happily.' },
    { word: 'log', hint: 'A thick section of a cut tree trunk for a campfire.' },
    { word: 'fog', hint: 'A misty cloud resting low right above the ground.' },
    { word: 'box', hint: 'A cardboard container used for wrapping presents.' },
    { word: 'fox', hint: 'A clever woodland animal with a bushy reddish tail.' },
    { word: 'top', hint: 'The highest point of a hill, or a spinning toy.' },
    { word: 'hop', hint: 'To jump lightly on one foot like a happy bunny.' },
    { word: 'pop', hint: 'A quick pleasant sound, like a bubble popping.' },
    { word: 'mop', hint: 'A cleaning tool with soft yarn used to wash floors.' },
    { word: 'pot', hint: 'A deep metal container for cooking vegetable soup.' },
    { word: 'hot', hint: 'Having a warm temperature; the opposite of cold.' },
    { word: 'dot', hint: 'A tiny round circle mark, like the dot above the letter i.' },
    { word: 'rod', hint: 'A long slender pole used for fishing.' },
    { word: 'jog', hint: 'To run at a steady, gentle, healthy pace.' },
    { word: 'cob', hint: 'The hard yellow core that holds sweet corn kernels.' },
    { word: 'pod', hint: 'The green shell that holds sweet little peas.' },
    { word: 'nod', hint: 'To move your head up and down to say yes.' },
    { word: 'lot', hint: 'A large amount of something, or an open plot of land.' },
    { word: 'cot', hint: 'A lightweight narrow folding bed used for camping.' },
    { word: 'rot', hint: 'What fallen autumn leaves naturally do to feed soil.' },
    { word: 'got', hint: 'Received something in the past.' },
    { word: 'not', hint: 'A word used to mean no or the opposite.' },
    { word: 'mom', hint: 'A loving mother.' },
    { word: 'mop', hint: 'Tool used with water to clean kitchen tiles.' },

    // Short U
    { word: 'sun', hint: 'The bright glowing star that lights up our daytime sky.' },
    { word: 'run', hint: 'To move quickly on your feet.' },
    { word: 'bus', hint: 'A big yellow vehicle that takes students to school.' },
    { word: 'cup', hint: 'A small container with a handle for drinking juice.' },
    { word: 'bug', hint: 'A tiny crawling insect in the garden.' },
    { word: 'hug', hint: 'To wrap your arms around someone you love.' },
    { word: 'mug', hint: 'A sturdy cup used for warm hot chocolate.' },
    { word: 'jug', hint: 'A large container with a spout for pouring milk.' },
    { word: 'rug', hint: 'A decorative soft mat on the living room floor.' },
    { word: 'mud', hint: 'Soft, wet earth after a refreshing rain shower.' },
    { word: 'nut', hint: 'A crunchy seed inside a hard shell, like a walnut.' },
    { word: 'hut', hint: 'A small, simple cabin made of logs or straw.' },
    { word: 'tub', hint: 'A large basin where you take bubble baths.' },
    { word: 'gum', hint: 'Chewy candy with fruity flavor.' },
    { word: 'pup', hint: 'A baby dog that loves to play and tumble.' },
    { word: 'fun', hint: 'Enjoyable activities that make you smile and laugh.' },
    { word: 'bun', hint: 'A round, soft bread roll for a veggie sandwich.' },
    { word: 'cub', hint: 'A cute young baby bear or lion.' },
    { word: 'sub', hint: 'A long sandwich roll or an underwater boat.' },
    { word: 'rub', hint: 'To move your hand back and forth over a surface.' },
    { word: 'tug', hint: 'To pull something firmly with a rope.' },
    { word: 'hum', hint: 'To make musical notes with your lips closed.' },
    { word: 'bud', hint: 'A baby flower getting ready to bloom in spring.' },
    { word: 'cut', hint: 'To divide paper into shapes using safety scissors.' },
    { word: 'gut', hint: 'Your tummy or inner instinct.' },
    { word: 'rut', hint: 'A groove in a dirt path made by bicycle wheels.' },
    { word: 'hub', hint: 'The central middle part of a spinning wheel.' },
    { word: 'yum', hint: 'What you say when eating something delicious.' },
    { word: 'sum', hint: 'The total answer when you add numbers together.' },

    // Sight & Nature Words
    { word: 'one', hint: 'The number that begins counting (1).' },
    { word: 'two', hint: 'The number that comes right after one (2).' },
    { word: 'see', hint: 'To look at the world with your eyes.' },
    { word: 'fly', hint: 'To glide through the air using wings.' },
    { word: 'sky', hint: 'The high blue ceiling above where clouds drift.' },
    { word: 'day', hint: 'The bright hours between sunrise and sunset.' },
    { word: 'boy', hint: 'A young male child.' },
    { word: 'toy', hint: 'An item made for playing and having fun.' },
    { word: 'joy', hint: 'A feeling of deep happiness and delight.' },
    { word: 'cow', hint: 'A gentle farm animal that eats grass and says moo.' },
    { word: 'owl', hint: 'A wise nocturnal bird that hoots at night.' },
    { word: 'bee', hint: 'A striped buzzing insect that makes sweet honey.' },
    { word: 'ant', hint: 'A tiny hardworking insect that lives in colonies.' },
    { word: 'ape', hint: 'A smart primate like a chimpanzee.' },
    { word: 'elk', hint: 'A large deer with majestic antlers in the forest.' },
    { word: 'yak', hint: 'A shaggy, long-haired ox living in high mountains.' },
    { word: 'fox', hint: 'A clever wild animal with reddish fur.' },
    { word: 'hen', hint: 'A mother chicken.' },
    { word: 'pig', hint: 'A farm animal that likes playing in mud.' },
    { word: 'rat', hint: 'A small animal with long whiskers.' },
    { word: 'bat', hint: 'A creature that flies at night using echolocation.' },
    { word: 'dog', hint: 'Man best friend that barks and wags.' },
    { word: 'cat', hint: 'A whiskered pet that loves chasing yarn.' },
    { word: 'sun', hint: 'The giant ball of light in outer space.' },
    { word: 'sea', hint: 'A vast expanse of blue saltwater.' },
    { word: 'ice', hint: 'Frozen water that is cold and slippery.' },
    { word: 'tea', hint: 'A warm herbal drink brewed in a teapot.' },
    { word: 'pie', hint: 'A baked pastry filled with sweet apples or cherries.' },
    { word: 'egg', hint: 'What a baby bird hatches out of in the nest.' },
    { word: 'oak', hint: 'A giant sturdy tree that grows acorns.' },
    { word: 'elm', hint: 'A tall shade tree with graceful green branches.' },
    { word: 'fir', hint: 'An evergreen pine tree that stays green all year.' },
    { word: 'fog', hint: 'Mist in the morning air.' },
    { word: 'dew', hint: 'Tiny water drops on morning grass blades.' },
    { word: 'ray', hint: 'A single straight beam of warm sunlight.' },
    { word: 'bay', hint: 'A curved body of calm ocean water along a coast.' },
    { word: 'hay', hint: 'Dried sweet grass fed to horses on a farm.' },
    { word: 'way', hint: 'A trail or direction to travel along.' },
    { word: 'may', hint: 'The cheerful spring month after April.' },
    { word: 'say', hint: 'To speak words aloud with your voice.' },
    { word: 'pay', hint: 'To give coins or dollars when buying goods.' },
    { word: 'lay', hint: 'To put down gently on a table or pillow.' },
    { word: 'zoo', hint: 'A park where people can view fascinating animals.' },
    { word: 'fur', hint: 'The soft warm coat of hair on a cat or bear.' },
    { word: 'car', hint: 'A four-wheeled passenger automobile.' },
    { word: 'jar', hint: 'A clear glass container with a screw-on lid.' },
    { word: 'tar', hint: 'Dark sticky material used when paving smooth roads.' },
    { word: 'bar', hint: 'A solid piece of chocolate or a gymnastics rail.' },
    { word: 'far', hint: 'A long distance away; not nearby.' },
    { word: 'raw', hint: 'Fresh uncooked vegetables like crisp carrots.' },
    { word: 'paw', hint: 'The soft padded foot of a puppy or kitten.' },
    { word: 'jaw', hint: 'The bone of the mouth that holds your teeth.' },
    { word: 'saw', hint: 'A tool with teeth for cutting wood, or viewed in past.' },
    { word: 'law', hint: 'A rule created to keep communities fair and safe.' },
    { word: 'bow', hint: 'A tied ribbon on a gift or what an archer shoots with.' },
    { word: 'row', hint: 'To propel a wooden canoe using oars.' },
    { word: 'tow', hint: 'To pull another vehicle behind using a cable.' },
    { word: 'sow', hint: 'To plant seeds into garden soil in springtime.' },
    { word: 'low', hint: 'Close to the floor or ground; not high.' },
    { word: 'mow', hint: 'To trim green garden grass with a lawnmower.' },
    { word: 'now', hint: 'At this present immediate moment.' },
    { word: 'how', hint: 'In what way or by what method.' },
    { word: 'cow', hint: 'A gentle bovine animal that gives milk.' },
    { word: 'wow', hint: 'An exclamation of pleasant surprise and wonder.' },
    { word: 'new', hint: 'Recently made or bought; not old.' },
    { word: 'few', hint: 'A small number of items; not many.' },
    { word: 'sew', hint: 'To join fabric together using a needle and thread.' },
    { word: 'key', hint: 'A metal tool used to unlock a door.' }
  ],

  2: [
    // --- TIER 2: 4-Letter Words & Consonant Blends (Grade 1 - 2) ---
    // L-Blends
    { word: 'blow', hint: 'To send a stream of air from your mouth.' },
    { word: 'blue', hint: 'The beautiful color of the clear sky and oceans.' },
    { word: 'blot', hint: 'A spot or stain of ink on paper.' },
    { word: 'blob', hint: 'A soft, round drop of paint or dough.' },
    { word: 'blur', hint: 'Something that is not clear to see.' },
    { word: 'clam', hint: 'A sea creature living inside a two-hinged shell.' },
    { word: 'clap', hint: 'To strike your hands together to show approval.' },
    { word: 'clay', hint: 'Soft moldable earth used for making pottery.' },
    { word: 'clip', hint: 'A small fastener that holds papers together.' },
    { word: 'clog', hint: 'A wooden shoe or when a drain gets blocked.' },
    { word: 'club', hint: 'A group of friends who share a fun hobby.' },
    { word: 'flap', hint: 'To move wings up and down to fly.' },
    { word: 'flat', hint: 'Smooth and level without bumps.' },
    { word: 'flag', hint: 'A piece of cloth with symbols waving in the wind.' },
    { word: 'flee', hint: 'To run away quickly from danger.' },
    { word: 'flip', hint: 'To turn something over, like a pancake.' },
    { word: 'flow', hint: 'To move steadily along like a stream of water.' },
    { word: 'glad', hint: 'Feeling happy, pleased, and cheerful.' },
    { word: 'glen', hint: 'A narrow, peaceful secluded valley.' },
    { word: 'glow', hint: 'To shine with a steady, gentle light.' },
    { word: 'plug', hint: 'An electrical connector or a stopper for a bathtub.' },
    { word: 'plum', hint: 'A sweet purple or red fruit with smooth skin.' },
    { word: 'plus', hint: 'The mathematical addition sign (+).' },
    { word: 'plot', hint: 'The storyline of a book or a garden patch.' },
    { word: 'play', hint: 'To have fun engaging in games with friends.' },
    { word: 'plan', hint: 'An organized idea worked out before taking action.' },
    { word: 'slam', hint: 'To close a door loudly with force.' },
    { word: 'slap', hint: 'A quick tap with the open palm of a hand.' },
    { word: 'sled', hint: 'A vehicle that glides over snow on winter hills.' },
    { word: 'slid', hint: 'Glided smoothly across slippery ice in the past.' },
    { word: 'slim', hint: 'Slender, thin, and graceful.' },
    { word: 'slip', hint: 'To slide accidentally on a wet surface.' },
    { word: 'slot', hint: 'A narrow opening, like where a coin is dropped.' },
    { word: 'slug', hint: 'A slow-moving garden creature like a snail without a shell.' },

    // R-Blends
    { word: 'brag', hint: 'To boast with pride about yourself.' },
    { word: 'bran', hint: 'Healthy outer cereal flakes of grain.' },
    { word: 'brim', hint: 'The top edge of a cup or hat.' },
    { word: 'crab', hint: 'A sea creature with ten legs and strong claws.' },
    { word: 'crop', hint: 'Plants like wheat or corn grown by farmers.' },
    { word: 'cram', hint: 'To pack lots of things tightly into a backpack.' },
    { word: 'drip', hint: 'Water falling in tiny individual drops.' },
    { word: 'drop', hint: 'A small bead of rain or to let something fall.' },
    { word: 'drum', hint: 'A musical instrument played by beating with sticks.' },
    { word: 'frog', hint: 'A green amphibian that hops and catches flies.' },
    { word: 'fret', hint: 'To worry needlessly about small things.' },
    { word: 'from', hint: 'Indicating the starting point or sender of a gift.' },
    { word: 'free', hint: 'Not held back; also costing zero dollars.' },
    { word: 'grab', hint: 'To take hold of something quickly with your hand.' },
    { word: 'gram', hint: 'A metric unit used for measuring light weight.' },
    { word: 'grid', hint: 'A pattern of criss-crossing horizontal and vertical lines.' },
    { word: 'grim', hint: 'Serious and stern in expression.' },
    { word: 'grin', hint: 'A big, joyful, beaming smile.' },
    { word: 'grip', hint: 'To hold on tightly with your fingers.' },
    { word: 'grit', hint: 'Courage and determination to keep trying.' },
    { word: 'prep', hint: 'To get ready beforehand for an activity.' },
    { word: 'prod', hint: 'To poke or encourage gently.' },
    { word: 'prop', hint: 'An object used on stage by actors in a play.' },
    { word: 'tram', hint: 'An electric rail car running along city streets.' },
    { word: 'trap', hint: 'A device made to catch things.' },
    { word: 'tree', hint: 'A tall wooden plant with branches and leaves.' },
    { word: 'trek', hint: 'A long, rewarding hike through the wilderness.' },
    { word: 'trim', hint: 'To clip neatly with scissors.' },
    { word: 'trip', hint: 'A fun journey or vacation to visit new places.' },
    { word: 'trot', hint: 'A gentle bouncing run by a friendly pony.' },

    // S-Blends
    { word: 'scan', hint: 'To look over quickly or digitize a document.' },
    { word: 'scab', hint: 'A protective crust that forms over a healed scrape.' },
    { word: 'skid', hint: 'To slide sideways on a slick road.' },
    { word: 'skim', hint: 'To remove cream from milk or read through quickly.' },
    { word: 'skin', hint: 'The outer protective layer covering your body.' },
    { word: 'skip', hint: 'To hop lightly along alternating feet.' },
    { word: 'skit', hint: 'A short, funny comedic theatrical play.' },
    { word: 'smog', hint: 'Hazy fog mixed with air particles.' },
    { word: 'snap', hint: 'To make a clicking sound with your fingers.' },
    { word: 'snip', hint: 'To cut with quick small scissor clips.' },
    { word: 'snug', hint: 'Warm, cozy, and comfortably fitted.' },
    { word: 'span', hint: 'The full length from one end to another.' },
    { word: 'spat', hint: 'A tiny brief disagreement between friends.' },
    { word: 'spin', hint: 'To rotate round and round rapidly.' },
    { word: 'spit', hint: 'To eject water from the mouth after brushing teeth.' },
    { word: 'spot', hint: 'A round dot, or a favorite location in a park.' },
    { word: 'spun', hint: 'Twisted threads together into yarn in the past.' },
    { word: 'step', hint: 'To lift a foot and place it forward to walk.' },
    { word: 'stem', hint: 'The main stalk supporting a green flower.' },
    { word: 'stop', hint: 'To come to a complete halt.' },
    { word: 'stub', hint: 'A short leftover piece of a pencil or ticket.' },
    { word: 'swim', hint: 'To paddle and move smoothly through water.' },
    { word: 'swan', hint: 'A graceful white waterbird with a long neck.' },
    { word: 'sway', hint: 'To swing gently back and forth like tree branches.' },

    // Ending Blends & Magic E
    { word: 'band', hint: 'A musical group of musicians playing instruments.' },
    { word: 'hand', hint: 'The part of your body with five fingers.' },
    { word: 'land', hint: 'Solid ground rather than ocean water.' },
    { word: 'sand', hint: 'Fine grains of crushed rock found on beaches.' },
    { word: 'pond', hint: 'A small body of calm freshwater.' },
    { word: 'wind', hint: 'Moving air that flies kites and turns windmills.' },
    { word: 'fend', hint: 'To defend or care for yourself.' },
    { word: 'lend', hint: 'To let a friend borrow a book.' },
    { word: 'mend', hint: 'To sew and repair a tear in a favorite shirt.' },
    { word: 'send', hint: 'To mail a postcard or message to someone.' },
    { word: 'bond', hint: 'A strong connection of friendship between people.' },
    { word: 'fond', hint: 'Having affection or warm liking for something.' },
    { word: 'bank', hint: 'A safe place where money is saved and kept.' },
    { word: 'pink', hint: 'A delicate color made by mixing red and white.' },
    { word: 'sink', hint: 'A basin with running water for washing hands.' },
    { word: 'wink', hint: 'To quickly close and open one eye as a friendly sign.' },
    { word: 'tank', hint: 'A glass aquarium where goldfish swim happily.' },
    { word: 'link', hint: 'A single loop in a chain or a website address.' },
    { word: 'rank', hint: 'A level or grade in scouts or martial arts.' },
    { word: 'bunk', hint: 'Stacked twin beds used in cozy cabins.' },
    { word: 'dunk', hint: 'To dip a warm cookie into a glass of milk.' },
    { word: 'tent', hint: 'A portable fabric shelter used when camping.' },
    { word: 'hunt', hint: 'To search carefully for hidden items, like treasure.' },
    { word: 'vent', hint: 'An opening that allows fresh air to circulate.' },
    { word: 'sent', hint: 'Delivered a letter in the mail in the past.' },
    { word: 'rent', hint: 'To pay to use a bicycle or cabin for a week.' },
    { word: 'bent', hint: 'Curved out of a straight line.' },
    { word: 'dent', hint: 'A small hollow mark pressed into a metal surface.' },
    { word: 'hint', hint: 'A helpful clue that leads you to an answer.' },
    { word: 'lint', hint: 'Tiny fuzzy fibers gathered on clothing.' },
    { word: 'mint', hint: 'A fresh green herb with a cool, pleasant flavor.' },
    { word: 'pint', hint: 'A unit of liquid measurement equal to two cups.' },
    { word: 'pant', hint: 'To breathe fast after a fun race.' },
    { word: 'camp', hint: 'To stay outdoors in nature overnight.' },
    { word: 'lamp', hint: 'A tabletop device providing electric reading light.' },
    { word: 'jump', hint: 'To push off the ground into the air.' },
    { word: 'pump', hint: 'A device used to inflate bicycle tires.' },
    { word: 'bump', hint: 'A small raised spot on a smooth road.' },
    { word: 'lump', hint: 'A compact chunk of clay or sugar.' },
    { word: 'ramp', hint: 'A slanted pathway useful for rolling wheels.' },
    { word: 'damp', hint: 'Slightly wet or moist; not fully dry.' },
    { word: 'melt', hint: 'To turn from solid ice into liquid with warmth.' },
    { word: 'belt', hint: 'A strap worn around the waist to hold pants up.' },
    { word: 'felt', hint: 'A soft colorful craft fabric, or touched in past.' },
    { word: 'colt', hint: 'A spirited young male horse.' },
    { word: 'bolt', hint: 'A threaded metal pin secured with a nut.' },
    { word: 'jolt', hint: 'A sudden brief bump or surge of surprise.' },
    { word: 'nest', hint: 'A cozy home woven by birds from twigs.' },
    { word: 'vest', hint: 'A sleeveless garment worn over a shirt.' },
    { word: 'fast', hint: 'Moving at high speed; swift.' },
    { word: 'best', hint: 'Of the highest possible excellence and quality.' },
    { word: 'rest', hint: 'To relax quietly and regain energy.' },
    { word: 'rust', hint: 'Reddish coating formed on iron exposed to rain.' },
    { word: 'dust', hint: 'Fine dry powder particles settled on shelves.' },
    { word: 'past', hint: 'Time that has already happened before today.' },
    { word: 'cast', hint: 'A plaster wrap that protects a healing bone.' },
    { word: 'cost', hint: 'The price required to buy a book or toy.' },
    { word: 'lost', hint: 'Unable to be found; not knowing your location.' },
    { word: 'post', hint: 'A wooden stake in the ground, or to mail a letter.' },
    { word: 'test', hint: 'A quiz or check to see how much you know.' },
    { word: 'west', hint: 'The compass direction where the sun sets.' },
    { word: 'list', hint: 'A series of items written down on paper.' },
    { word: 'mist', hint: 'A fine spray of tiny water droplets in the air.' },
    { word: 'soft', hint: 'Pleasantly smooth and gentle to touch.' },
    { word: 'loft', hint: 'An upper open room located under a roof.' },
    { word: 'raft', hint: 'A flat floating platform used on lakes.' },
    { word: 'gift', hint: 'A wrapped present given to make someone happy.' },
    { word: 'lift', hint: 'To raise something up into the air.' },
    { word: 'sift', hint: 'To pass flour through a fine wire mesh screen.' },
    { word: 'left', hint: 'The opposite direction of right.' },
    { word: 'fact', hint: 'A piece of information that is proven true.' },
    { word: 'duct', hint: 'A tube or pipe carrying warm air through rooms.' },
    { word: 'pact', hint: 'A formal promise or agreement between friends.' },

    // Double Consonants & Magic E
    { word: 'duck', hint: 'A waterbird with webbed feet and a yellow bill.' },
    { word: 'rock', hint: 'A solid mass of minerals found in nature.' },
    { word: 'lock', hint: 'A mechanism secured with a brass key.' },
    { word: 'sock', hint: 'A soft garment worn on your foot inside shoes.' },
    { word: 'neck', hint: 'The part of the body connecting head to shoulders.' },
    { word: 'peck', hint: 'A quick tap with a bird beak.' },
    { word: 'deck', hint: 'An outdoor wooden patio attached to a house.' },
    { word: 'back', hint: 'The rear part of your body opposite the chest.' },
    { word: 'pack', hint: 'To put clothes neatly inside a suitcase.' },
    { word: 'rack', hint: 'A metal stand for holding coats or spices.' },
    { word: 'sack', hint: 'A large sturdy bag made of burlap or canvas.' },
    { word: 'tack', hint: 'A short small nail with a broad flat head.' },
    { word: 'kick', hint: 'To strike a soccer ball with your foot.' },
    { word: 'pick', hint: 'To choose a favorite flower from a meadow.' },
    { word: 'tick', hint: 'The soft rhythmic sound made by a clock.' },
    { word: 'bake', hint: 'To cook delicious muffins in a warm oven.' },
    { word: 'cake', hint: 'A sweet dessert served at birthday celebrations.' },
    { word: 'make', hint: 'To create, build, or construct something new.' },
    { word: 'lake', hint: 'A large calm body of freshwater surrounded by land.' },
    { word: 'take', hint: 'To grasp and carry something with you.' },
    { word: 'wake', hint: 'To stop sleeping and start a brand new day.' },
    { word: 'rake', hint: 'A long-handled garden tool used to gather autumn leaves.' },
    { word: 'bike', hint: 'A two-wheeled vehicle steered with handlebars.' },
    { word: 'hike', hint: 'A long scenic walk along mountain trails.' },
    { word: 'like', hint: 'To enjoy or appreciate something.' },
    { word: 'kite', hint: 'A light cloth craft flown high up in the wind.' },
    { word: 'bite', hint: 'To cut food with your teeth.' },
    { word: 'site', hint: 'A location where a building or campfire is placed.' },
    { word: 'ride', hint: 'To sit on a bicycle or carousel horse and travel.' },
    { word: 'side', hint: 'An edge or border of a geometric shape.' },
    { word: 'tide', hint: 'The rise and fall of ocean water twice daily.' },
    { word: 'wide', hint: 'Spanning a large distance across; not narrow.' },
    { word: 'hide', hint: 'To stay out of sight in a secret spot.' },
    { word: 'line', hint: 'A straight stroke drawn on a piece of paper.' },
    { word: 'mine', hint: 'Belonging to me, or an underground quarry.' },
    { word: 'nine', hint: 'The number between eight and ten (9).' },
    { word: 'pine', hint: 'An evergreen needle tree with pinecones.' },
    { word: 'vine', hint: 'A climbing woody plant that produces juicy grapes.' },
    { word: 'fine', hint: 'Very good, healthy, or made of delicate threads.' },
    { word: 'home', hint: 'The cozy house where you live with family.' },
    { word: 'bone', hint: 'Hard white structure that forms the skeleton.' },
    { word: 'cone', hint: 'A 3D shape pointed at top, like an ice cream cone.' },
    { word: 'tone', hint: 'The musical pitch or quality of a sound.' },
    { word: 'zone', hint: 'A designated region, like a school zone.' },
    { word: 'rope', hint: 'Strong thick braided cord used for climbing.' },
    { word: 'hope', hint: 'A cheerful feeling of expecting good things.' },
    { word: 'rose', hint: 'A beautiful sweet-scented garden flower with thorns.' },
    { word: 'nose', hint: 'The facial organ used for breathing and smelling.' },
    { word: 'hose', hint: 'A flexible rubber tube for watering gardens.' },
    { word: 'pose', hint: 'To stand still in a position for a photograph.' },
    { word: 'hole', hint: 'An opening or hollow spot in the ground.' },
    { word: 'mole', hint: 'A furry little animal that digs underground tunnels.' },
    { word: 'pole', hint: 'A tall straight rod, like the North Pole or flagpole.' },
    { word: 'sole', hint: 'The bottom underside of your shoe or foot.' },
    { word: 'tube', hint: 'A hollow cylinder, like a tube of toothpaste.' },
    { word: 'mule', hint: 'A hardworking farm animal with long ears.' },
    { word: 'cube', hint: 'A 3D box shape with six identical square sides.' },
    { word: 'cute', hint: 'Sweet, charming, and delightful to see.' },
    { word: 'mute', hint: 'Silent; having the sound turned off.' },
    { word: 'fuse', hint: 'A safety device that protects electrical circuits.' },
    { word: 'dune', hint: 'A hill of wind-blown golden sand in a desert.' },
    { word: 'tune', hint: 'A catchy melody composed of musical notes.' },
    { word: 'rule', hint: 'A guideline designed to keep everyone safe.' },
    { word: 'bell', hint: 'A hollow metal chime that rings when struck.' },
    { word: 'ball', hint: 'A round bouncy sphere used in soccer and tennis.' },
    { word: 'call', hint: 'To speak loudly to get someone attention.' },
    { word: 'fall', hint: 'The autumn season when leaves turn orange.' },
    { word: 'tall', hint: 'Reaching high above average height.' },
    { word: 'wall', hint: 'A vertical brick or wooden side of a room.' },
    { word: 'hall', hint: 'A long corridor inside a school or house.' },
    { word: 'mall', hint: 'A large indoor shopping center with many stores.' },
    { word: 'fill', hint: 'To pour water into a glass until it is full.' },
    { word: 'hill', hint: 'A raised mound of green land smaller than a mountain.' },
    { word: 'mill', hint: 'A building where grain is ground into flour.' },
    { word: 'pill', hint: 'Medicine shaped in a small solid tablet.' },
    { word: 'will', hint: 'Determination and intention to succeed.' },
    { word: 'doll', hint: 'A toy figure shaped like a human child.' },
    { word: 'roll', hint: 'To move forward by turning over and over.' },
    { word: 'toll', hint: 'A small fee paid to drive across a scenic bridge.' },
    { word: 'bull', hint: 'A strong male bovine on a farm.' },
    { word: 'full', hint: 'Holding as much as possible; not empty.' },
    { word: 'pull', hint: 'To exert force on an object to draw it closer.' },
    { word: 'puff', hint: 'A short light breath or cloud of steam.' },
    { word: 'cuff', hint: 'The folded fabric band at the bottom of a sleeve.' },
    { word: 'mess', hint: 'An untidy state of toys on the floor needing cleanup.' },
    { word: 'less', hint: 'A smaller amount or quantity.' },
    { word: 'kiss', hint: 'A gentle sign of affection on a cheek.' },
    { word: 'miss', hint: 'To fail to catch a ball, or to think fondly of someone.' },
    { word: 'pass', hint: 'To throw a basketball to a teammate.' },
    { word: 'bird', hint: 'A feathered creature that sings in tree branches.' },
    { word: 'moon', hint: 'The glowing orb illuminating the night sky.' },
    { word: 'star', hint: 'A twinkling point of celestial light in outer space.' },
    { word: 'book', hint: 'Bound pages containing stories and illustrations.' },
    { word: 'fish', hint: 'A water-dwelling creature with gills and shiny scales.' },
    { word: 'cave', hint: 'A natural hollow rock chamber inside a mountain.' },
    { word: 'wave', hint: 'A ridge of water rolling onto a sandy beach.' },
    { word: 'gate', hint: 'A swinging wooden or iron barrier in a fence.' },
    { word: 'late', hint: 'Arriving after the scheduled start time.' }
  ]
};

console.log('Generating expanded dictionary for Tiers 1-8...');

// Verify counts
for (let t in TIER_DATA) {
  console.log(`Tier ${t} template words: ${TIER_DATA[t].length}`);
}
