name: Deploy to Firebase Hosting on PR
on: pull_request
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npx vitest run
      - run: npm run build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/171658556844/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
          service_account: github-action-1311198724@kibo-climb.iam.gserviceaccount.com
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: kibo-climb
